name: banking-system
services:
  postgres:
    image: postgres:alpine
    container_name: banking-system-postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banking-system

  redis:
    image: redis:alpine
    container_name: banking-system-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

  mail:
    container_name: banking-system-mail
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - MP_DATABASE=/data/mailpit.db
      - TZ=Asia/Saigon
    volumes:
      - mailpit_data:/data

  minio:
    image: minio/minio:latest
    container_name: banking-system-minio
    ports:
      - '9000:9000'
      - '9001:9001' # MinIO Console port
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_DEFAULT_BUCKETS: 'banking-system'
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: banking-system-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: banking-system-grafana
    ports:
      - '6000:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_SERVER_ROOT_URL: 'http://localhost:6000'
    depends_on:
      - otel-collector
      - loki
      - jaeger

  loki:
    image: grafana/loki:latest
    container_name: banking-system-loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '14250:14250' # OTLP gRPC ingest
      - '14268:14268' # OTLP HTTP ingest (deprecated in Jaeger but still common)

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: banking-system-otel-collector
    command: ['--config=/etc/otel-collector/otel.yaml']
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    volumes:
      - ./otel-collector/otel.yaml:/etc/otel-collector/otel.yaml
    depends_on:
      - loki
      - jaeger

volumes:
  postgres-data:
  redis_data:
  minio_data:
  mailpit_data:
