apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: banking-system

spec:
  selector:
    app: banking-system
    component: redis

  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-port
