apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: banking-system

stringData:
  receipt_enc_master_key_v1: 'iMc7BjfEmZ0DdAr1qy6M8c9nVq6Ja+dY9n1s4TJV7z4='
  webhook_enc_master_key_v1: 'BLJWQ1QaItmgXcdkOd822YgK492fKA8txDPjqcxe+hM='
  jwt_secret: 's3cr3t'
  mail_transport: 'smtp://mail:1025' # there will be username and password later, so it's best to put it in secrets
