apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: banking-system

spec:
  selector:
    app: banking-system
    component: mail

  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: smtp-port
    - name: inbox
      protocol: TCP
      port: 8025
      targetPort: inbox-port
