events {}

http {
  upstream backend {
    server api1:5000 max_fails=3 weight=2 fail_timeout=10s;
    server api2:5000 max_fails=2 weight=2 fail_timeout=10s;
    server api3:5000 max_fails=3 weight=1 fail_timeout=10s;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

  }

  server {
    server_name jaeger.localhost;
    location / {
      proxy_pass http://jaeger:16686;
    }
  }

  server {
    server_name mail.localhost;
    location / {
      proxy_pass http://mail:8025;
    }
  }

  server {
    server_name grafana.localhost;
    location / {
      proxy_pass http://grafana:3000;
    }
  }

  server {
    server_name minio.localhost;
    location / {
      proxy_pass http://minio:9001;
    }
  }
}