apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: banking-system
spec:
  selector:
    matchLabels:
      app: banking-system
      component: postgres

  template:
    metadata:
      labels:
        app: banking-system
        component: postgres
        environment: production

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres-port
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_password

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_db
